version: '3'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
     - DB_URL=postgresql://postgres:123@flask_db:5432/weather
    depends_on:
      - flask_db
  flask_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: weather
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres-data: {}